"""fix

Revision ID: 1e7f0ca6b127
Revises: 90b961aad166
Create Date: 2026-01-02 16:20:10.550174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7f0ca6b127'
down_revision: Union[str, Sequence[str], None] = '90b961aad166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('release_assignments', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.create_index('idx_release_assignments_unique', 'release_assignments', ['release_id', 'user_id', 'role'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_release_assignments_unique', table_name='release_assignments')
    op.alter_column('release_assignments', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
