"""init

Revision ID: 3f840b55c1f2
Revises: 
Create Date: 2026-01-02 13:10:20.632377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f840b55c1f2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('name_ru', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('score', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('episodes', sa.Integer(), nullable=True),
    sa.Column('episodes_aired', sa.Integer(), nullable=True),
    sa.Column('aired_on', sa.String(), nullable=True),
    sa.Column('released_on', sa.String(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('search_prefix', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_releases_aired_on', 'releases', ['aired_on'], unique=False)
    op.create_index('idx_releases_chat_id', 'releases', ['chat_id'], unique=False)
    op.create_index('idx_releases_is_completed', 'releases', ['is_completed'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('roles', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('translator', sa.Text(), nullable=True),
    sa.Column('voice', sa.Text(), nullable=True),
    sa.Column('timing', sa.Integer(), nullable=True),
    sa.Column('curator', sa.Integer(), nullable=True),
    sa.Column('designer', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('release_id')
    )
    op.create_table('sent_episodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('torrent_url', sa.String(), nullable=True),
    sa.Column('magnet_link', sa.String(), nullable=True),
    sa.Column('page_link', sa.String(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sent_episodes_magnet', 'sent_episodes', ['magnet_link'], unique=False)
    op.create_index('idx_sent_episodes_release_ep', 'sent_episodes', ['release_id', 'episode'], unique=False)
    op.create_index('idx_sent_episodes_torrent', 'sent_episodes', ['torrent_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sent_episodes_torrent', table_name='sent_episodes')
    op.drop_index('idx_sent_episodes_release_ep', table_name='sent_episodes')
    op.drop_index('idx_sent_episodes_magnet', table_name='sent_episodes')
    op.drop_table('sent_episodes')
    op.drop_table('assignments')
    op.drop_table('users')
    op.drop_index('idx_releases_is_completed', table_name='releases')
    op.drop_index('idx_releases_chat_id', table_name='releases')
    op.drop_index('idx_releases_aired_on', table_name='releases')
    op.drop_table('releases')
    # ### end Alembic commands ###
