"""fix

Revision ID: 477d3fd2cf83
Revises: c6a5c978d05b
Create Date: 2026-01-02 14:26:22.665033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '477d3fd2cf83'
down_revision: Union[str, Sequence[str], None] = 'c6a5c978d05b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('release_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.Enum('TRANSLATOR', 'VOICE', 'TIMING', 'CURATOR', 'DESIGNER', name='userrole'), nullable=False),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_release_assignments_release', 'release_assignments', ['release_id'], unique=False)
    op.create_index('idx_release_assignments_release_role', 'release_assignments', ['release_id', 'role'], unique=False)
    op.create_index('idx_release_assignments_user', 'release_assignments', ['user_id'], unique=False)
    op.drop_table('assignments')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('assignments',
    sa.Column('release_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('translator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('voice', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timing', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('curator', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('designer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['release_id'], ['releases.id'], name=op.f('assignments_release_id_fkey')),
    sa.PrimaryKeyConstraint('release_id', name=op.f('assignments_pkey'))
    )
    op.drop_index('idx_release_assignments_user', table_name='release_assignments')
    op.drop_index('idx_release_assignments_release_role', table_name='release_assignments')
    op.drop_index('idx_release_assignments_release', table_name='release_assignments')
    op.drop_table('release_assignments')
    # ### end Alembic commands ###
